if __name__=='__main__':
	print("This script takes what's inside original.txt and copy it into copy.txt")
	f=open('original.txt')
	fileContent=f.read()
	w=open('copy.txt','w')
	w.write('The content of the original file is:\n')
	w.write('%s' %fileContent)
	w.close()
	w=open('copy.txt')
	copyContent=w.read()
	print('%s' %copyContent)
	f.close()
	w.close()